### ISSUE TITLE
Incorrect output for HtmlNode::outerHtml() after updating attributes

### ISSUE THREAD

**Issue by mallardduck** [paquettg/php-html-parser#100]
If you were to update an elements attributes and then call outerHtml() to get the new element you would expect to see the updated attributes in the DOM element provided. This is not the case, you are provided the original HTML for the element.

I'm fairly positive this is the same issue as #99 though it's coming up under different circumstances so I wanted to report this as it's own issue. I'll toy with a fix and see if I can submit a PR!

**Comment by mallardduck** [comment]
It looks like #88 is also tangentially related to this issue.

It's all a symptom of DOM/HTML cache not being cleared corrected when classes are modified.

**Comment by paquettg** [comment]
merged PR
