### ISSUE TITLE
PHP Fatal error:  Out of memory

### ISSUE THREAD

**Issue by llgoer** [paquettg/php-html-parser#105]
PHP Fatal error:  Out of memory (allocated 559939584) (tried to allocate 5557452
88 bytes) in \vendor\paquettg\php-html-parser\src
\PHPHtmlParser\Dom.php on line 535

**Comment by HarpyWar** [comment]
May be your source file is too large for the current PHP [memory_limit](http://php.net/manual/en/ini.core.php#ini.memory-limit) option?

**Comment by Gicminos** [comment]
I am loading regular websites that my PC opens with no problem, is it possible that they actually require more than 2GB of RAM to be parsed or we should investigate? (maybe it is one of the loop of the other issues?)
