### ISSUE TITLE
CURLOPT_USERAGENT

### ISSUE THREAD

**Issue by olimortimer** [paquettg/php-html-parser#107]
I can't seem to see any option to be able to set CURLOPT_USERAGENT, and finding that some sites will respond with 'Server Error in '/' Application' if this isn't set.

Is anyone aware of a way to set CURLOPT_USERAGENT using php-html-parser?  Setting the following (for example) below CURLOPT_CONNECTTIMEOUT in `/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Curl.php` fixes the error:

`curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.1) Gecko/20061204 Firefox/2.0.0.1');`

**Comment by ignatenkovnikita** [comment]
answer here #113
