### ISSUE TITLE
Issue using the "*" selector

### ISSUE THREAD

**Issue by stormrockwell** [paquettg/php-html-parser#109]
when I run js:  $( '#red-line-g *' ).length i get a count of 25.
when I run php: count( $dom->find( '#red-line-g *' ) ) i get a count of 51

Is there a better way to get all of the children?

**Comment by stormrockwell** [comment]
I found getChildren and that returns 51 too. there are only 25 children
http://pastebin.com/Rpr93WwG

**Comment by dogpixels** [comment]
Same problem here; DOM order is quite relevant in certain situations.

**Comment by paquettg** [comment]
This issue is fixed by having turning off the 'whitespaceTextNode' option.

We will make this the default behavior in the next major release.
