### ISSUE TITLE
Check if node exists

### ISSUE THREAD

**Issue by Ferikl** [paquettg/php-html-parser#111]
```
$dom = new Dom;
$dom->find('#frame1')
```
returns me not null result.
How can I determine if my node was found ?

**Comment by aliforever** [comment]
```
$Nodes = $dom->find('#frame1');
if (!count($Nodes)) {
    echo "not found";
}
```

**Comment by jadayash** [comment]
H

> ```
> $Nodes = $dom->find('#frame1');
> if (!count($Nodes)) {
>     echo "not found";
> }
> ```

This is throwing this exception
PHPHtmlParser\Exceptions\EmptyCollectionException
The collection does not contain any Nodes.

**Comment by muzanaka** [comment]
I found lifehack

$priceObj = $dom->find($parsePriceAttribute);
if(!empty($priceObj->toArray())){
    $price = $priceObj->innerHtml;
}

You can check, if empty array. It's works for me
