### ISSUE TITLE
Proxy is support?

### ISSUE THREAD

**Issue by ignatenkovnikita** [paquettg/php-html-parser#113]

**Comment by ignatenkovnikita** [comment]
I implements interface 
`class ParseClient implements CurlInterface
{


    /**
     * This method should return the content of the url in a string
     *
     * @param string $url
     * @return string
     */
    public function get($url)
    {
        $client = new Client();

        return $client->request('GET', $url, [
            'headers' => [
                'User-Agent' => 'testing/1.0',
//                'Accept'     => 'application/json',
//                'X-Foo'      => ['Bar', 'Baz']
            ],
            'proxy' => 'http://202.56.203.40:80'
        ])->getBody();

        // TODO: Implement get() method.
    }
}`

**Comment by ozonar** [comment]
Has anything changed in 2020? Following code is not working, class Client not exist?

**Comment by paquettg** [comment]
Hey,

we are working on a new version on dev, version 3, which does have a client refactor, yes. But this version is not live and should not have any effect on your code base unless you are using the most recent dev version with your code base.
