### ISSUE TITLE
Dom is loading, but find or some other method is not working.

### ISSUE THREAD

**Issue by ghulamakbar14** [paquettg/php-html-parser#119]
dom is working. But when I use 
$dom->find('input') or $dom->outerHTML it gives me null. I don't know what the issue is ? Anyone can please help ?

**Comment by ghulamakbar14** [comment]
@paquettg please check this

**Comment by michimawan** [comment]
i got the same issue, but after i adding option `cleanupInput => false` it works (return outerHtml as usual)

the default that stated in the readme was not right, it said false, but actually true

```
    protected $defaults = [
        'whitespaceTextNode' => true,
        'strict'             => false,
        'enforceEncoding'    => null,
        'cleanupInput'       => true,
        'removeScripts'      => true,
        'removeStyles'       => true,
        'preserveLineBreaks' => false,
    ];

```

**Comment by ghulamakbar14** [comment]
I got it fixed after changing to PHP5.6 on my local machine.
