### ISSUE TITLE
Class 'stringEncode\Encode' not found

### ISSUE THREAD

**Issue by Bizarrus** [paquettg/php-html-parser#12]
Fatal error: Class 'stringEncode\Encode' not found in /var/www/clients/client19/web83/web/libs/PHPHtmlParser/Dom.php on line 593

**Comment by paquettg** [comment]
hey,

I would like some more information on this problem. Your implementation seems to have trouble loading a class from a library we depend on to encode the content of the html pages. The fact that it could not be found makes me believe that you are not loading the package using composer as composer would ensure that the dependency is also loaded.
