### ISSUE TITLE
[Request] Edit TextNode

### ISSUE THREAD

**Issue by sohelzerdoumi** [paquettg/php-html-parser#125]
hi,
thank you for your project.

I really need to edit the content of a TextNode.
Can you add this feature? 

```php
class TextNode extends LeafNode
{
    public function setText($text)
    {
        $this->text = $text;
    }
}
```

thank you

**Comment by maedi** [comment]
Similarly it would be great to have this in `HtmlNode`:
```php
public function setOuterHtml($text)
{
  $this->outerHtml = $text;
}
```
This allows for easy replacing of elements:
```php
$element->setOuterHtml($new_element->outerHtml);
```

**Comment by paquettg** [comment]
I have added support for the setText method on text nodes.

If you still want support for adding inner HTML please open a new ticket and we can discus that possibility.
