### ISSUE TITLE
Find not work if this exist in html page??

### ISSUE THREAD

**Issue by nicolass2002** [paquettg/php-html-parser#128]
I try to parse one html page..and find not work if in html head exist this part of code:

<script>window.jQuery || document.write('<script src="src/js/vendor/jquery.min.js?v2.1.3"><\/script>')</script>

When I remove that part Find work???

How to avoid that when I parse that online web page?

**Comment by dwightnetzango** [comment]
I'm just getting started using this project, so I'm no expert.  

I'm only responding because nobody else has.
First, if you are in control of the code that generates that html, fix it.
I'm going to assume that it's someone else's html and you can't their html.
I no

**Comment by nicolass2002** [comment]
I just do like you say and work..I replace that part with blank..and then send to parser..and it work.
