### ISSUE TITLE
Get nth-child?

### ISSUE THREAD

**Issue by Luc45** [paquettg/php-html-parser#129]
Is it possible to do something like this?
`$dom->find('#tabs div.content.ui-tabs-panel')->child(2);`

To get this guy:
```
<div id="tabs">
    <div class="content ui-tabs-panel"></div>
    <div class="content ui-tabs-panel"></div> <!-- Here? -->
    <div class="content ui-tabs-panel"></div>
    <div class="content ui-tabs-panel"></div>
</div>
```

**Comment by dwightnetzango** [comment]
someone didn't read the readme
$dom->find('#tabs div.content.ui-tabs-panel',2);
Except, it's zero based, so you'll want to use 1 instead of 2

**Comment by sahifedp** [comment]
how to get latest child?
by css:  $dom->find('#tabs .content:last-child');
or jQuery:  $dom->find('#tabs .content:last-child')->last();

**Comment by dwightnetzango** [comment]
Just get the array, and pull the last value off the array.  I've actually stopped using this because of all it's limitations and the memory usages.   I've gone back to the native PHP processing.
