### ISSUE TITLE
Curly brackets cause unexpected behavior

### ISSUE THREAD

**Issue by draobrehtom** [paquettg/php-html-parser#131]
For example, if I'll use getElementsByClass, ng-class atribute returns empty; 

**Input:**
`<div class="nav-item" ng-click="go('/dashboard')" ngclass="{{active:isActive('/dashboard')}}">Home</div>`

**Output:**
`<div class="nav-item" ng-click="go('/dashboard')" ngclass="">Home</div>`

Another situation:

**Input:**
`<div class="title">{{$root.title}}</div>`

**Output:**
`<div class="title">{}</div>`

**Comment by draobrehtom** [comment]
Please, add it to Dom.php

```
// strip smarty scripts
if ($this->options->get('removeSmarty') == true) 
{
        $str = mb_eregi_replace("(\{\w)(.*?)(\})", '', $str);
}
```

**Comment by csimpi** [comment]
You should fork and make the changes then make a merge request because this issue is very odd.

**Comment by paquettg** [comment]
The option to change this behavior has been added to 2.1.0.

For more information, please look at issue #184
