### ISSUE TITLE
[QUESTION] : Does this package supports php 7.1 ?

### ISSUE THREAD

**Issue by neorganic** [paquettg/php-html-parser#138]
Does this package supports php 7.1 ?

**Comment by plonknimbuzz** [comment]
go here for new future https://github.com/thesoftwarefanatics/php-html-parser for 7.2 supported 

see this maybe help you https://github.com/paquettg/php-html-parser/pull/126#issuecomment-356625323

**Comment by paquettg** [comment]
Yes, 2.0.0 supports it.
