### ISSUE TITLE
text node breaking firstChild()

### ISSUE THREAD

**Issue by nats12** [paquettg/php-html-parser#142]
Hi, what exactly is meant to happen if an element's first child is a text node? It's just breaking down on me with error `Child '' not found in this node.` Here's a small snippet of my code:

**foreach($seededElements as $element) {
	$foundElement = $dom->find($element->name);
	$count = count($foundElement);
	.....
        foreach($foundElement as $foundEl) {
		$childElement = $foundEl->firstChild();**

Errors just after that $childElement line as it's brought back a '' node.

Btw, I have the whitespaceTextNode option set to false at the beginning.

**Comment by paquettg** [comment]
I have added a test for this issue in a116fe170f26b51d71745a2fd0b89850da749361 and was not able to reproduce it.

Please let me know if you continue to experience this issue.
