### ISSUE TITLE
Issue with Parsing in this URL

### ISSUE THREAD

**Issue by amitbsconcept** [paquettg/php-html-parser#145]
URL - http://www.thehindu.com/life-and-style/travel/travel-to-kerala-for-the-best-indian-adventure/article24033246.ece

When i try parsing the same using the following
```
$dom->loadFromUrl($url);
die($dom->outerHtml); 
```
What happens in here is - it throws out incomplete content. It breaks the output beyond a point for some reason. 

I went and dug deeper - tried till checking if there is any issue with clean method in Dom.php - till there it is absolutely clean - no worries. It is when i am trying to print the HTML output - it is failing to print out completely.

Can someone please help me on the same?

**Comment by enocryph** [comment]
@amitbsconcept i think the problem is because page uses [ajax](https://en.wikipedia.org/wiki/AJAX) for complete build
