### ISSUE TITLE
Tag replacement not working 

### ISSUE THREAD

**Issue by nirajkmr** [paquettg/php-html-parser#149]
Hi ,
I tried to replace the tag with the new amp-img tag, but its not replacing the tag.Could you please help on this asap.

`<?php
require "vendor/autoload.php";
use PHPHtmlParser\Dom\MockNode as Node;
use PHPHtmlParser\Dom;
use PHPHtmlParser\Dom\HtmlNode;
use PHPHtmlParser\Dom\TextNode;
use PHPHtmlParser\Dom\MockNode;
use PHPHtmlParser\Dom\InnerNode;
use PHPHtmlParser\Dom\Tag;
$dom = new Dom;
$dom->load('<p>For the past few years, Bollywood actresses have been turning heads at the coveted Cannes Film Festival red carpet. While Aishwarya Rai Bachchan is all set to make her 16th appearance at the French Riviera, Huma Qureshi, who made her debut at the Cannes Film Festival, looked heavenly in a white customised Varun Bahl corset skirt and cape accessorised with Suhani Pittie earrings and Malone Souliers shoes. The actress opted for minimal makeup contrasted with a dark shade of lipstick with her hair pulled back in a neatly tied bun.</p> <blockquote> <p>Huma Qureshi is attending the 71st Cannes Film Festival in association with liquor brand Grey Goose and will be a part of brand curated events at the festival.</p></blockquote><div class="embeddedContent oembed-provider- oembed-provider-instagram" data-align="none" data-oembed="https://www.instagram.com/p/Bij9LVSlp1U/?hl=en&amp;taken-by=iamhumaq" data-oembed_provider="instagram" data-resizetype="noresize"> <amp-instagram layout="responsive" data-shortcode="Bij9LVSlp1U" width="640" height="799"></amp-instagram></div><p>Niraj</p>');
$a = $dom->find('.oembed-provider-instagram');
 $tag = new Tag('amp-img');

        //$src = $a->getAttribute('src') ?: $a->getAttribute('data-src');
        $tag->setAttribute('src', 'https://www.dike.lib.ia.us/images/sample-1.jpg/image_view_fullscreen');

        $html = new HtmlNode($tag);

        $a->getParent()->replaceChild($a->id(), $html);
	echo $html;`

**Comment by IamSAB** [comment]
``` html
$dom = new Dom;

foreach($dom->find('...') as $node) {
    $tmpl = new Dom;
    // do some stuff
    $node->getParent()->replaceChild($node->id(), $tmpl->root);
}

var_dump($dom->__toString()); // outputs string(1) " "
```

Can't do it either.

**Comment by paquettg** [comment]
This issue appears to already be resolved. I am going to close this issue.

Please let me know if you are still experiencing this issue.
