### ISSUE TITLE
setAttribute does not work without an array as value

### ISSUE THREAD

**Issue by frazehmad** [paquettg/php-html-parser#15]
On home page of this repo, I see an example of setting an attribute:

```
$tag->setAttribute('class', 'foo');
```

But above code does not work and through below error:

*Illegal string offset 'value'*

But If I use an array for second parameter then it works fine:

```
$tag->setAttribute('class', array('value'=>'foo', 'doubleQuote'=>true));
```

**Comment by paquettg** [comment]
I'll take a look at it.
