### ISSUE TITLE
loadFromFile() does not work, gives error "count(): Parameter must be an array or an object that implements Countable - failed. Retrying..."

### ISSUE THREAD

**Issue by connecteev** [paquettg/php-html-parser#153]
loadFromFile() does not work, gives the following error:
count(): Parameter must be an array or an object that implements Countable - failed. Retrying...

Code:
$url = 'http://www.ask.com';
$html = new Dom();
$html->loadFromFile($url);

When you run these commands, the console shows the following error:
count(): Parameter must be an array or an object that implements Countable - failed. Retrying...

Also tried the following, with the same error in the console:
$url = 'http://www.ask.com';
$html = new Dom();
$html->load($url);
count(): Parameter must be an array or an object that implements Countable - failed. Retrying...

**Comment by alcaeus** [comment]
See https://github.com/paquettg/php-html-parser/pull/126#issuecomment-356625323

**Comment by paquettg** [comment]
Fixed in 2.0.0
