### ISSUE TITLE
The code breaks with error

### ISSUE THREAD

**Issue by cspdabbler** [paquettg/php-html-parser#158]
For me the code breaks when $rule['tag'] is not an array with error **count(): Parameter must be an array or an object that implements Countable**

https://github.com/paquettg/php-html-parser/blob/96634727ec973ee0a57c5060139bfd747f079b67/src/PHPHtmlParser/Selector.php#L171

**Comment by alcaeus** [comment]
I'll just paste one of my previous comments here.

> A fix for this issue has been merged into a dev branch without any further activity. If you want to use PHP 7.2 or later, read https://github.com/paquettg/php-html-parser/pull/126#issuecomment-356625323.

**Comment by cspdabbler** [comment]
Thanks @alcaeus

**Comment by paquettg** [comment]
Resolved in 2.0.0
