### ISSUE TITLE
LoadFromUrl parameter type not compatible with the member of the interface

### ISSUE THREAD

**Issue by akhmadfauzi** [paquettg/php-html-parser#163]
I made a simple request based on the example in a php file, then run in on Windows CLI PHP 7.3, however it throw an exception as follows.
```
PHP Fatal error:  Declaration of PHPHtmlParser\Curl::get(string $url): string must be compatible with PHPHtmlParser\CurlInterface::get($url): string in C:\Users\Fauzi\Desktop\CURLIB\vendor\paquettg\php-html-parser\src\PHPHtmlParser\Curl.php on line 11
```

Based on the response, i've tried to resolved the problem by updating the CurlInterface file to :
`public function get(string $url): string;` 
I added the parameter type, and it works

**Comment by phh** [comment]
Fix here: https://github.com/paquettg/php-html-parser/pull/162
