### ISSUE TITLE
Cannot add attribute

### ISSUE THREAD

**Issue by eagle-r** [paquettg/php-html-parser#17]
There is no way to add a new attribute to a tag. For example, I wanted to add `ng-app='appName'` to an HTML tag

Using the setAttribute method results in,
```
[ErrorException]
  Illegal string offset 'value'
```

Ideally, the setAttribute method should create a new attribute if it doesn't exist yet.

**Comment by paquettg** [comment]
This is solved on master... I guess I should have release it as a minor patch so this issue would not have come up.

https://github.com/paquettg/php-html-parser/commit/858ec467af55856e5026e8990db9d85e6f2aef62

You can use the 
"paquettg/php-html-parser": "dev-master" 
revision number in composer to get the most recent version of the code which will solve this issue. I'll update the version number as soon as I solve your other issue.

cheers!
