### ISSUE TITLE
Supported php versions

### ISSUE THREAD

**Issue by Rolige** [paquettg/php-html-parser#170]
Hi, nice script, congratulations!

More than reporting an incident, I could ask you, what versions of php are supported?, in your README you said **We support php 7.1, 7.2, and 7.3.**, its not clear if your script supports only these versions or simply clarify this have support for these versions.

Regards!

**Comment by paquettg** [comment]
Hey @Rolige ,

We only run our unit tests against the versions listed in the README and will only provide support for these versions. It might work with 7.0, but I do not test against version of PHP not supported by PHP anymore (It will not work in 5.X as it uses a lot of 7.0 features).

Hope that helps.
