### ISSUE TITLE
Wrong elements order

### ISSUE THREAD

**Issue by AliN11** [paquettg/php-html-parser#173]
Hi. Consider this string (note that the first `img` tag is between `p` tag):
```html
$str = '<p><img src="http://example.com/first.jpg"></p><img src="http://example.com/second.jpg">';
```

With this PHP code:
```php
$dom = (new Dom)->load($str);
$images = $dom->find('img');

foreach ($images as $image) {
    echo $image->src;
}
```

**Expected output**:
```
http://example.com/first.jpg
http://example.com/second.jpg
```
**Actual output**:
```
http://example.com/second.jpg
http://example.com/first.jpg
```

Furthermore, below code returns second element. while it should return first element:
```php
$image = $dom->find('img', 0);
$image->src; // http://example.com/second.jpg
```
I mean, I get wrong elements order. Any help?

**Comment by kevjett** [comment]
I'm getting the same issue, anyone found how to fix?

**Comment by AliN11** [comment]
@kevjett 
I didn't find any solution. So I used [https://simplehtmldom.sourceforge.io/](url)

**Comment by paquettg** [comment]
The current implementation orders it breath first, which was not intended.

Since this would be a backwards incompatible bug fix I'll add a configuration in 2.1.0 and I'll make it the default, correct, behavior in 3.0.0.

Thanks for reporting the issue. If you find a solutions please create a PR.

**Comment by paquettg** [comment]
I have added an option 'depthFirstSearch' to give you the correct behavior. As this is a backwards breaking change I am going to create a new ticket to change the default behavior in 3.0.0.

**Comment by andrisi** [comment]
Hello @paquettg I think this bug still exists in version 2.2.1. I can reproduce if getting the below URL, then searching for ".notAccessibleForFree" then for "p" elements below it. They're returned, but not in the order they're in the HTML, regardless of the depthFirstSearch option. I can see that the IDs are not in numberical order wether this option is true or false.

https://www-telegraph-co-uk.cdn.ampproject.org/v/s/www.telegraph.co.uk/royal-family/2020/02/22/bitter-desperate-clear-harry-meghan-dont-plan-quit-firm-quietly/amp/?amp_js_v=0.1
