### ISSUE TITLE
Mistake in parsing of included scripts

### ISSUE THREAD

**Issue by DenisYakimchuk** [paquettg/php-html-parser#175]
Construction like
```
<script>window.jQuery || document.write('<script src="js/jquery-3.3.1.min.js" defer><\/script>')</script>
 	<script src="js/jquery.main.js" defer></script>
```
is parsing as a single script inclusion.
I mean the innerHtml of all of that is
`window.jQuery || document.write('<script src="js/jquery-3.3.1.min.js" defer><\ />cript>')</script> <script src="js/jquery.main.js" defer></script>`

**Comment by paquettg** [comment]
Hey,

Scripts are removed by default. If you want to include scripts as part of the innerHtml of nodes 

If you want to not do this, you can modify the `removeScripts` option, as documented https://github.com/paquettg/php-html-parser#options.

I am going to close this issue, please let me know if I misunderstood your request.
