### ISSUE TITLE
I am having an error with the htmlnode.php when my script is online.

### ISSUE THREAD

**Issue by ressilzafra** [paquettg/php-html-parser#181]
Can someone help me with this problem? Thanks in advance. 

PHP Fatal error:  Uncaught TypeError: Return value of PHPHtmlParser\Dom\HtmlNode::clear() must be an instance of PHPHtmlParser\Dom\void, none returned in /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/HtmlNode.php:196
Stack trace:
#0 /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/InnerNode.php(438): PHPHtmlParser\Dom\HtmlNode->clear()
#1 /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/InnerNode.php(169): PHPHtmlParser\Dom\InnerNode->setParent(Object(PHPHtmlParser\Dom\HtmlNode))
#2 /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(570): PHPHtmlParser\Dom\InnerNode->addChild(Object(PHPHtmlParser\Dom\HtmlNode))
#3 /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(209): PHPHtmlParser\Dom->parse()
#4 /home/270804.cloudwaysapps.com/ in /-----/public_html/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/HtmlNode.php on line 196

**Comment by salvatorecapolupo** [comment]
Same problem with any URL, while integrating into WordPress using composer.

**Comment by defunctl** [comment]
Which PHP version are you guys running?

**Comment by defunctl** [comment]
Yeah, that method is type casted as `void` which was added in PHP 7.1

**Comment by paquettg** [comment]
Yes, we do not support PHP 7.0, which appears to be the issue here.

I am going to close off this issue, please feel free to let me know if this assumption is in correct.
