### ISSUE TITLE
< in script block breaks parsing in 2.1.0

### ISSUE THREAD

**Issue by gfeld** [paquettg/php-html-parser#188]
The following example returns zero.
```
count((new Dom())->load('
<html>
<head>
    <script type="text/javascript">
        console.log(1 < 3);
    </script>
</head>
<body>
    <div id="panel"></div>
</body>
</html>
', ['removeScripts' => false])->find('body'));
```

if I comment out the following lines in Dom.php

```
        if (trim($tag) == '')
        {
            // no tag found, invalid < found
            return $return;
        }
```
everything works as expected

**Comment by paquettg** [comment]
Hey @gfeld ,

I found the issue but a proper solution is difficult to implement in version 2 of the module.

I will fix this as part of the update in version 3 but I will not implement a solution for version 2. If you would like, please feel free to create a PR with a fix for the current version.

Thank you,.
