### ISSUE TITLE
Find does not search in descendants of matches

### ISSUE THREAD

**Issue by BjarkeNL** [paquettg/php-html-parser#189]
Thanks for a cool project. Found an issue:

The find() method does not find all matches. After it has found a DOM-node that matches, it seems that it does not keep searching the children of that node for more matches.

Example: (5 b-tags should have been found, but only two are found)

```PHP
$html = "
    <p>
        <b>
            test
            <b>testing</b>
            <b>This is a test</b>
            <i>italic</i>
            <b>password123</b>
        </b>
        <i><b>another</b></i>
    </p>";

$dom = new Dom();
$dom->loadStr($html);
$nodes = $dom->find('b');
echo count($nodes);

```

Of course, there is no exact specification in the documentation of how ->find() should work, but it is indicated that it should work like JQuery, so i'm thinking it's not how it was intended. (As an aside: would be nice with documentation of the API)

(The same happens for getElementsByTag() and possibly others)

Version: 2.1.0

**Comment by paquettg** [comment]
Hey,

I am marking this as a backwards breaking change as this behavior is probably expected/abused by some one who uses the module. I do agree that this is not proper behavior though, so I will change it in 3.0.0.

**Comment by MasterOdin** [comment]
For reference, the standard JS toolkit of interacting with DOM does a proper recursive search:
```
> let a = document.createElement('div');
<div>​</div>​
> a.innerHTML = '<div><span>what<span>Test</span></span></div>';
"<div><span>what<span>Test</span></span></div>"
> a.getElementsByTagName('span');
HTMLCollection(2) [span, span]
> a.querySelectorAll('span')
NodeList(2) [span, span]
```
