### ISSUE TITLE
support php 7.3?

### ISSUE THREAD

**Issue by reimax** [paquettg/php-html-parser#199]
test code:

require_once '/vendor/php-html-parser/vendor/autoload.php';
$dom = new \PHPHtmlParser\Dom;
$dom->load([some html code]);
$order_title = $dom->find('.class')[0]->text;

return empty result. I test on php 7.2 and my code work and result not empty.

**Comment by paquettg** [comment]
Hey @reimax ,

Can you please provide the same html code that is causing you the issue?

Thank you.

**Comment by reimax** [comment]
i parse https://www.fl_ru/projects/4243062/dodelat-programmu-winapi-c.html
.b-page__title - try get title

**Comment by Chuanhsing** [comment]
Ubuntu 20.04, PHP 7.4.3 broken too.

```
$contents = file_get_contents("https://poe.garena.tw/gpc-news");
$dom = new Dom;
$dom->load($contents);
$contents = $dom->find('.row');
```

Works fine at Ubuntu 18.04, PHP 7.2

**Comment by paquettg** [comment]
This has been updated as part of 3.0.0
