### ISSUE TITLE
AbstractNode::resetCount() breaks node id uniqueness

### ISSUE THREAD

**Issue by Taitava** [paquettg/php-html-parser#203]
Hi, this issue description is long, as I will describe it step by step.

https://github.com/paquettg/php-html-parser/blob/12b94f69637f946ca35af6554f0da67d9d176ca8/src/PHPHtmlParser/Dom/AbstractNode.php#L71-L78
This part explains well how node ids are generated and what they look like. It's a running number starting from 0. `AbstractNode::$count` is increased every time a new node is created, so every node should get a unique id, right?

Well, not always.

https://github.com/paquettg/php-html-parser/blob/12b94f69637f946ca35af6554f0da67d9d176ca8/src/PHPHtmlParser/Dom/AbstractNode.php#L139-L147
I don't know the reason why the counter should be reset, but here we have a method that does it. 

https://github.com/paquettg/php-html-parser/blob/12b94f69637f946ca35af6554f0da67d9d176ca8/src/PHPHtmlParser/Dom.php#L147-L160
According to my IDE, this is the only place where `AbstractNode::resetCount()` is called. I still don't see, why it's called. And see: `Dom::load()` is one kind of a wrapper: it inspects the value of `$str` and calls one of these other methods:
 - `loadFromFile()`,
 - `loadFromUrl()`,
 - or `loadStr()`
None of those methods call `AbstractNode::resetCount()`, and all of those methods are public, so it's easy to bypass `resetCount()` by just avoiding the `load()` method completely, and calling one of the specific `loadFrom*()` methods mentioned above.

**Finally: what is the problem with `AbstractNode::resetCount()`?**
Well, it does bad things!
Lets take an example where we want to insert one new element into a dom:
```php
// Create a dom which will be used as a parent/container for a paragraph
$dom1 = new \PHPHtmlParser\Dom;
$dom1->load('<div>A container div</div>'); // Resets the counter (doesn't matter here as the counter was 0 even without resetting)
$div = $dom1->firstChild();
echo 'Div id: '. $div->id().'<br>'; // Outputs 1

// Create a paragraph outside of the first dom
$dom2 = new \PHPHtmlParser\Dom;
$dom2->load('<p>Our new paragraph.</p>'); // Resets the counter
$paragraph = $dom2->firstChild();
echo 'Paragraph id: '. $paragraph->id(); // Outputs 1
```

(Just a note before continuing the example: when `$dom1`/`$dom2` is loaded with HTML content, it will have actually two nodes instead of just one: both doms will have an invisible `root` element which will have an id of 0. This is why the `div`/`p` element will have an id of 1 instead of 0.)

But let's continue with the example:

```php
$div->addChild($paragraph);
```
This will throw a `CircularException`, because take a look at the `InnerNode::addChild()` method:
https://github.com/paquettg/php-html-parser/blob/12b94f69637f946ca35af6554f0da67d9d176ca8/src/PHPHtmlParser/Dom/InnerNode.php#L110-L122

The last check will make it to: CRASH! BOOM! "The numbers are BAD!!" (says Hurley from the most legendary TV show, Lost.)

**Comment by paquettg** [comment]
Hey,

Thank you for bringing this to my attention. I found the commit that added this method, 

https://github.com/paquettg/php-html-parser/commit/4cb1619542168aefb44f56abe667d81bd57e8af9#diff-f75fce80d714de7d836d9c2c3030371fR115-R119

but I can't tell why this was changed from the original code. I think we should update this code to use the original code and remove the counter completely.

As removing this method is backwards in compatible I'll add this to the release of version 3.

**Comment by Taitava** [comment]
Thanks! :)

yea, I think it's a good idea to remove the counter and generate the id the way it was done before: `$this->id = spl_object_hash($this);`

**Comment by Taitava** [comment]
Hmm, just to make sure, is it actually needed to remove `findById()` in 4bb7098f3a46582dd9c5cd289fae6f0e835f2916 ? Would it be enough to only remove `resetCount()`?

I can't remember if I do use `findById()` or not, but could it be useful for some situations?

**Comment by paquettg** [comment]
Hey,

I removed findById() as I don't feel like the package should need to support getting elements out of it by ID. I just can't think of a way to do this and it was not documented as a feature.

I am aware it is not backwards compatible, hence why it is part of version 3.0.0.

If you can think of a good use case for this I can add it back, that would be great.

**Comment by Taitava** [comment]
Ok, I understand. I just checked my own project, I don't use `findById()` anywhere. :)
