### ISSUE TITLE
mb_eregi_replace() expects parameter 3 to be string

### ISSUE THREAD

**Issue by Samson1964** [paquettg/php-html-parser#209]
Uncaught PHP Exception TypeError: "mb_eregi_replace() expects parameter 3 to be string, null given" at /paquettg/php-html-parser/src/PHPHtmlParser/Dom.php line 535

Fix: `$str = mb_eregi_replace('"\s+>', '">', $str);` to `$str = mb_eregi_replace('"\s+>', '">', (string)$str);` in row 535 and 531

**Comment by nikserg** [comment]
@Samson1964 's answer didn't work out in my case. The error was gone, but `find` function returned no results. Turned out, it was a charset problem. You need to pass string in `utf8` only. I converted my string from original charset to `utf8` and it worked.
```
$content = iconv('windows-1251', 'utf-8', $content);
$dom->load($content);
```
