### ISSUE TITLE
htmlSpecialCharsDecode=true and strict=false

### ISSUE THREAD

**Issue by dartess** [paquettg/php-html-parser#216]
'strict' => false,
            'htmlSpecialCharsDecode' => true,

Should this combination work? I got a problem with an attribute with no value:

```
<iframe src="some" frameborder="0" allowfullscreen  height="460" width="100%"></iframe>
```

**Comment by paquettg** [comment]
the strict takes makes it so that all attributes must have a value, something like allowfullscreen="allowfullscreen" would be how to you would make custom boolean attributes.

You can always turn off strict to make attribute with no value valid.
