### ISSUE TITLE
index-related selector ?

### ISSUE THREAD

**Issue by gordielachance** [paquettg/php-html-parser#22]
Hi, 
It seems that index-related selectors does not work ?

I need to have a selector to get the second matched item, like

    $node = $html->find('a:eq(1)')

I can't use 

    $nodes = $html->find('a');
    $node = $nodes[1];

in my script, I need to get it using a selector.

Any way to achieve this ?

Thanks.

**Comment by tegansnyder** [comment]
Try:
```php
$node = $html->find('a')[1]
```
That will give you the 2nd `a` element (zero based index).
