### ISSUE TITLE
"mb_eregi_replace() expects parameter 3 to be string" in Dom->loadStr

### ISSUE THREAD

**Issue by alexinside** [paquettg/php-html-parser#220]
Exception "mb_eregi_replace() expects parameter 3 to be string"
often thrown from 
 $dom->loadStr($content, []);

This (found in the internet) fixes it:
 /paquettg/php-html-parser/src/PHPHtmlParser/Dom.php line 535
Fix: $str = mb_eregi_replace('"\s+>', '">', $str); to $str = mb_eregi_replace('"\s+>', '">', (string)$str); in row 535 and 531

Version: 2.2.1

**Comment by paquettg** [comment]
This should be resolved in the version 3.0.0 branch/tag.

Please try it their and re-open the ticket if you are still experiencing this issue.
