### ISSUE TITLE
Breaks when encountering non tag-related <

### ISSUE THREAD

**Issue by reveance** [paquettg/php-html-parser#221]
There should probably be a check whether the encountered tag is valid, just like a browser would interpret it. For example, when parsing the following content:
`<p>Hello, this is just a test in which <55 names with some other text > should be interpreted as text</p>`
However the `<55 names with some other text >` is instead interpreted as a `55` tag which breaks a lot of functionality. I don't think this should break in non-strict mode.

**Comment by reveance** [comment]
For anyone that encounters the same issue and is okay with an extremely hacky solution, you could put the following code inside the `} else { ... }` below 
`$position = strpos($this->content, $string, $this->pos);` 
in the function `copyUntil` in `Content.php`:
`while($string === '<' && !preg_match('/^[a-zA-Z\/]$/', (string) $this->char($position + 1)) && $this->pos + 1 != $this->size) {
    $position = strpos($this->content, $string, $position + 1);
}`

**Comment by joao-pedro-alves** [comment]
same here...

**Comment by reveance** [comment]
> The **<** sign should be written with **&lt;** and **>** written with **&gt;**, so if you put string like **<hello world>**, the machine will read them as a tag. It is normal, like when we create custom tags in HTML.

Yes, that's why I said it should not break in **strict** mode. In a perfect world it would indeed be written this way, however since browsers don't break on these issues, the websites' owners are probably not even aware that they have these issues. Meaning it is unlikely to even be fixed. Since we still need to crawl, it would be nice to have the parser behave more in terms of what a browser would do, meaning to not break on this issue.

**Comment by paquettg** [comment]
in version 3.0.0 this string does not break anymore. The string in the original comment will not turn into 

```
<p>Hello, this is just a test in which <55 names with some other text> should be interpreted as text</55></p>
```

and be parsed with out any issue. I am still working on this version of the project so if you have any feedback please let me know.
