### ISSUE TITLE
 Uncaught TypeError: mb_eregi_replace() expects parameter 3 to be string, null given

### ISSUE THREAD

**Issue by staude** [paquettg/php-html-parser#227]
HI, i receive this error
Fatal error: Uncaught TypeError: mb_eregi_replace() expects parameter 3 to be string, null given in projekt/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php:535

when i try to load this url with oadFromUrl
https://wordpress.tv/2009/08/29/custom-fields-introduction/

**Comment by paquettg** [comment]
Resolved this issue as part of the 3.0.0 release.

This will most likely be released to master very soon. All I have to do is finish updating the documentation.
