### ISSUE TITLE
VS Code Intellisense reporting `Undefined method 'insertBefore'`

### ISSUE THREAD

**Issue by nbrombal** [paquettg/php-html-parser#228]
I've noticed that my IDE (VS Code) has been highlighting the `insertBefore` method as unknown despite the fact that it works as expected. I took a quick peek and found that it's likely just a matter of documentation.

An `AbstractNode`'s parent is documented as being an `InnerNode` (or null):
https://github.com/paquettg/php-html-parser/blob/c116346b2fcc038d4ab6615f4328346a4eebf121/src/PHPHtmlParser/Dom/Node/AbstractNode.php#L44-L49

But the `getParent` method is documented as returning an `AbstractNode`:
https://github.com/paquettg/php-html-parser/blob/c116346b2fcc038d4ab6615f4328346a4eebf121/src/PHPHtmlParser/Dom/Node/AbstractNode.php#L154-L162

I'm not 100% sure what the documented return types _should_ be, but at the very least they don't seem to match here, which is ultimately causing Intellisense to interpret something as broken.

Thanks a ton for this great library!

**Comment by paquettg** [comment]
I have updated the getParent method to return the innerNode, which is accurate.
