### ISSUE TITLE
innertext not reflecting the new value

### ISSUE THREAD

**Issue by chaudigv** [paquettg/php-html-parser#229]
`use PHPHtmlParser\Dom;`

`$html = new Dom;`

`$html->loadStr('<div class="main_print_frame"><span class="d_input" data-name="institute_name">Progress Academy</span></div>');`

`foreach($html->find('.d_input') as $element) {
    $element->innertext = 'Future Academy';
}`

`dd($html->innertext); // still showing Progress Academy`

**Comment by paquettg** [comment]
The innerText property is read only, you can not edit it.

I have updated the documentation to reflect this.
