### ISSUE TITLE
css selector bug

### ISSUE THREAD

**Issue by ahmadmll** [paquettg/php-html-parser#231]
hi sir
i want to use a below selector ::
"div>p"
for below html ::
<div class="test"><p>okkkk</p></div>
by below code 

$dom = new Dom;
$dom->loadStr('<div class="test"><p>olllllllll</p></div>');
$a = $dom->find('div>p');
echo $a->count();

but i got error ::
Uncaught PHPHtmlParser\Exceptions\EmptyCollectionException: The collection does not contain any Nodes

please help me

**Comment by paquettg** [comment]
Hey,

if you put a space in between the div and > and p it will work, so something like this

```php
        $dom = new Dom();
        $dom->loadStr("
        <div>
          <p>olllllllll</p>
        </div>");
        $a = $dom->find("div > p");
        $this->assertEquals(1, $a->count());
```

Hope that helps.
