### ISSUE TITLE
How can I add proxy & verify guzzle  option in Dom Object?  

### ISSUE THREAD

**Issue by YashPatel2020** [paquettg/php-html-parser#234]
I need these two options in Dom Object. 
 How can I do that?
(1) http://docs.guzzlephp.org/en/stable/request-options.html#verify
(2) http://docs.guzzlephp.org/en/stable/request-options.html#proxy

**Comment by paquettg** [comment]
If you create your own client and request object you can pass it trough the third and fourth param for the `loadFromUrl` method. This will allow you to create your own client and request object which you can customize as you wish.

Hope that helps.
