### ISSUE TITLE
AWS SDK issues relating to Guzzle 7.x

### ISSUE THREAD

**Issue by nicklaw5** [paquettg/php-html-parser#239]
Just wanted to open a quick issue to say that I've had to pin this dependency to `v3.0.1` in my project due to [this open issue](https://github.com/aws/aws-sdk-php/issues/2057) with the AWS PHP SDK not playing nice with Guzzle `7.x`.

Feel free to close this issue. I just thought it might be helpful to others that stumble across this same problem.

**Comment by evaleries** [comment]
Same here with laravel http client

**Comment by nicklaw5** [comment]
This appears to have been resolved by https://github.com/aws/aws-sdk-php/pull/2117. I've returned to using `v3.1.0` of this library after updating to the latest version of the AWS SDK (`v3.158.6`).
