### ISSUE TITLE
Unable to find element using child selector '>'

### ISSUE THREAD

**Issue by FrancisBaileyH** [paquettg/php-html-parser#24]
Firstly, let me say thanks for maintaining such a great library, it has been exceptionally useful in my project. But on to the issue

Using the following code:

``` php
$dom->find('div > ul');
```
Results in an empty set, despite the html being valid. It seems the find() function does not support child selectors. I added in a unit test to SelectorTest.php to confirm the results.

**The test code:**
``` php
	public function testFindClassWithChildSelector() {
		
		$root   = new HtmlNode(new Tag('root'));
		$parent = new HtmlNode(new Tag('div'));
		$child1 = new HtmlNode(new Tag('ul'));	
		$root->addChild($parent);
		$parent->addChild($child1);
		
		$selector = new Selector('div > ul');
		$this->assertEquals(1, count($selector->find($root)));
	}
```

**The results:**
![php-html-parser-test-failed](https://cloud.githubusercontent.com/assets/4231049/8632501/91be776e-2752-11e5-9fdf-710253988e2f.png)

I'm going to see if I can't add the functionality myself. However, given your familiarity with the library you may be able to make a quick change to fix this.

**Comment by tegansnyder** [comment]
@FrancisBaileyH did you ever add this functionality. I've been getting around this by loading the innerHtml of the parent back into a dom and traversing. I wrote a little function that takes an array of dom values to traverse and does this.

**Comment by FrancisBaileyH** [comment]
Hi @tegansnyder, I ended up using, Symfony's DomCrawler and CssSelector components, which allow for similar jQuery DOM traversals. I had to drop use of this library as modifying the functions was going to be too time consuming.
