### ISSUE TITLE
find() returns nothing

### ISSUE THREAD

**Issue by harveencensus** [paquettg/php-html-parser#244]
Using the find method I am looking for an element, but whenever I alway get an empty object, even though the elements exists. 

$dom->find("html"));

The statement above returns 
![Schermafbeelding 2020-10-05 om 13 18 53](https://user-images.githubusercontent.com/53259901/95073581-637c6c80-070d-11eb-99b8-cc623169e04f.png)

**Comment by paquettg** [comment]
you will need to provide a sample of the html and then we can help you.

I'll close off this ticket and we can re-open it.

Thank you.
