### ISSUE TITLE
Cannot install on PHP 7.1

### ISSUE THREAD

**Issue by waltertamboer** [paquettg/php-html-parser#246]
The composer.json file in version 3.1 specifies that PHP version 7.1 or higher is required. At the same time it requires guzzlehttp/guzzle:^7.0. Version 7 of guzzlehttp/guzzle requires at least PHP version 7.2 so this results in a conflict making it impossible to install the library.

https://github.com/paquettg/php-html-parser/blob/b200ae9894af3ba309115c120799f3f273d3e2aa/composer.json#L16
https://github.com/paquettg/php-html-parser/blob/b200ae9894af3ba309115c120799f3f273d3e2aa/composer.json#L22

**Comment by paquettg** [comment]
Hey,

php 7.1 is no longer supported by the core and is not receiving security updates, that is why we do not support it. I did forget to update the version flag, I will do so this weekend.

Thank you for letting me know.
