### ISSUE TITLE
Stripping style and script tags in clean function

### ISSUE THREAD

**Issue by robertclarkson** [paquettg/php-html-parser#25]
Hey mate, great module, just started using it, just wondering why i can't pull out any script tags, and i can see they're getting stripped in your clean() function.

This could be just what you want, but i'm actually wanting to parse these out! Ah well could just fork it ay.

Thanks again.
Cheers
Rob

**Comment by paquettg** [comment]
Hey robert,
You are correct that, currently, we remove all script tags to make it easier to parse the html file. If you can come up with a solution in your fork that can handle parsing the script tag with out incorrectly removing html/including html tags that should not be please send us a pull request.

Thanks.
