### ISSUE TITLE
Can the find feature use regx to search for things?

### ISSUE THREAD

**Issue by mooror** [paquettg/php-html-parser#27]
As the title states above, I am wondering if the find feature use regx to search for things and if so how.

Thanks,
Mooror

**Comment by paquettg** [comment]
The find feature does use some regex but mainly to parse the input to find (https://github.com/paquettg/php-html-parser/blob/master/src/PHPHtmlParser/Selector.php#L14) but it does not use regex after this point.

Most of the logic that is behind find can be found in the Selector.php file I linked above.

I hope this helps.

**Comment by mooror** [comment]
Thank you for the reply.Cheers
