### ISSUE TITLE
Script cleaner can break down html

### ISSUE THREAD

**Issue by asergiychuk** [paquettg/php-html-parser#28]
If i meet something like that
```html
    <p>.....</p>
    <script>
        some code ....
        document.write("<script src='some script'><\/script>")
        some code ....
    </script>
    <p>....</p>
```
cleaner remove many of html body

It can fix by chane code:
```php
    $str = preg_replace("'<\s*script[^>]*[^/]>(.*?)<\s*/\s*script\s*>'is", '', $str);
```
to 
```php
$str = preg_replace("'<\s*script[^>]*[^/]>(.*?)<[^\/]*/\s*script\s*>'is", '', $str);
```

**Comment by paquettg** [comment]
I could not duplicate the issue, I added a test in the commit above but, using the string you gave me, I am getting the correct result.

If you could provide a test case that fails and shows the issue, please create a pull request so I can fix it (or you could fix it and submit a pull request + test).

Thanks.
