### ISSUE TITLE
install without composer?

### ISSUE THREAD

**Issue by rainman20** [paquettg/php-html-parser#30]
is it possible to install this without composer? I am testing this on Wamp Server on Windows and planning to use in shared hosting so is there any possible installation without using composer?

**Comment by mooror** [comment]
I am not the developer of this repo, so I don't know the answer to your first question. But I wondered if you tried installing composer via the windows install tool and setting the php path to your wamp servers php file. I tried this on my windows ampps install (which is quite similar to wamp) and it worked just fine.

Hope that helps,
Mooror

**Comment by paquettg** [comment]
Hey @rainman20 ,
We do not support installing without composer as composer handles all the auto loading of the classes in the package. It also makes it a lot easier to share the package using packagist.

That being said, I don't see why you can use composer in your set up, as @mooror said.

**Comment by FMaz008** [comment]
A self-contained package would have been helpful in my case as well.
