### ISSUE TITLE
select element that has specific text

### ISSUE THREAD

**Issue by alireza9402** [paquettg/php-html-parser#32]
hi!
how i can select a element that has a specific text?

And a suggestion :
in css or jquery when i want select a element with two class i use this syntax .class1.class2
but in your script it doesn't work.i think you choose this syntax for this : .class1+.class2
please fix this.Thank You.

**Comment by alireza9402** [comment]
i found a solution.i use this way to select element :  .class{SomeText}

**Comment by alireza9402** [comment]
i write this function and add that to Dom.php.
    public function findWithText($selector, $text)
    {
        $this->isLoaded();
        $results = $this->find($selector);
        $return = new Collection;
        foreach($results as $result){
            if($result->text == $text){
                $return[] = $result;
            }
        }
        return $return;
    }

**Comment by paquettg** [comment]
Is there a normal way to do this (selecting elements with text) in css/jquery?

Could you also open another issue with the double class issue. I would like to keep each issue dedicated to a single problem.

Thanks.

**Comment by alireza9402** [comment]
no jquery has this syntax  $(":contains(text)")

**Comment by paquettg** [comment]
I have not been able to get this to work. If some one else can find a solution to this please send me a pull request but I am not able to modify the regex to get this suntax to work, sorry.

**Comment by doncadavona** [comment]
JQuery has this selector syntax:

`"a:contains('https://google.com')"`

Any alternate way to use the same function meanwhile its not supported yet?
