### ISSUE TITLE
HTML attributes with double quotes in them break parsing

### ISSUE THREAD

**Issue by dirtside** [paquettg/php-html-parser#37]
Given this HTML:

`<a title="This is a "test" of double quotes" href="http://www.example.com">Hello</a>`

When passed into `Dom::load()`, the parser ends up correctly finding the element, but misparses the attributes and body text. The attributes (from `var_dump($element->getAttributes())`) appear like so:

`array(1) {
  ["title"]=>
  string(10) "This is a "
}`

and the body appears like so (from `var_dump($element->text())`):

`string(58) "est" of double quotes" href="http://www.example.com">Hello"`

I realize that putting double quotes inside an attribute is noncomformant to HTML, but ideally PHPHtmlParser should be tolerant of such things and parse the element anyway, much in the way web browsers do. While it may be impossible to accurately determine what the intended `title` attribute's correct value is, it should be possible to ensure that the element text does not include content from before the `>` marker.

**Comment by paquettg** [comment]
I agree that we should handle this. I am more curious in knowing how you think we should handle this. 

I have a few ideas but I am not fully aware of how browsers do this. If you have any insight into this or any ideas please let me know.

thanks

**Comment by dirtside** [comment]
Ultimately it comes down to detecting the `>` that ends the start tag, which can be tricky if there's multiple `>` inside other attributes in the tag, or an uneven number of `"` marks spread across one or more attributes. I assume browsers use some complicated heuristics, but messing around with various befunged attributes in Firefox, it looks like it treats the first `>` that's not inside an attribute (that is, not between a matching pair of `"` marks) as the end of the open tag. Everything after that (until a `<`) is considered part of the body of the element.

So there'd be two main (non-nominal) cases: an attribute with an extra pair of unescaped `"` inside of it (e.g. `<a title="This "is" an attribute">`), and an attribute with _one_ extra `"` inside it (e.g. `<a title="This "is an attribute">`). The former is obviously easier; the latter could be treated as having one attribute called `title` with value `This `, and three other attributes named `is`, `an`, and `attribute`, each with empty values (the `"` immediately after `attribute` would be discarded as an invalid token since you can't have a double quote after an attribute name, there has to be an `=` first). The `>` is thus not inside an attribute, from the parser's POV, and ends the tag.

Another edge case is something like this: `<span title=">something</span>`. Firefox discards the entire thing as unparseable.

Presumably the corresponding logic can be found (somewhere) in the vast Firefox (Gecko?) and Chrome (Chromium) codebases.
