### ISSUE TITLE
'Illegal string offset 'value''

### ISSUE THREAD

**Issue by ruigomeseu** [paquettg/php-html-parser#39]
I'm using this package to read some HTML and replace all anchor tags with some other href (to be more specific, I have coded a function _getRedirectUrl_ that follows all redirects and gets the final URL after all redirections, but this is not relevant for the issue I'm running into).

This is the code I've came up with:

```php
$dom = new Dom;
$dom->load($content);

$links = $dom->find('a');

foreach($links as $link)
{
    $finalUrl = $this->getRedirectUrl($link->getAttribute('href'));
    $tag = $link->getTag();
    $tag->setAttribute('href', $finalUrl);
}

return trim(strip_tags($dom->root->innerHtml(), '<p><a><img>'));
```

$content contains very simple HTML, something like:

```
<div>
Actual content

<a href="http://bit.ly/1jIDoCy">This is a link</a>

<a href="http://bit.ly/1N0ZM5s">This is another one</a>

Parse this.
</div>
```

The final $dom->root->innerHtml() fails with:

```
local.ERROR: exception 'ErrorException' with message 'Illegal string offset 'value'' in /home/vagrant/Code/marketer/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/Tag.php:161
```

Am I doing something wrong? I'd appreciate any help, I've spent the past day trying to fix it to with no success.

**Comment by ruigomeseu** [comment]
I managed to fix this by changing the minimum stability of the package to "dev-master" on my composer.json file.

The latest package Packagist finds for this package is 1.6.4, and not 1.6.7 as it should.

**Comment by paquettg** [comment]
Wow... I did notice this.... this was caused by me not keeping up to date with the version field in the composer.json. I removed that field and the next tag should solve this issue.
