### ISSUE TITLE
Losing Line Breaks when getting ->innerHtml

### ISSUE THREAD

**Issue by sc0ttkclark** [paquettg/php-html-parser#40]
Looks like html is losing line breaks when getting `$dom->find( '.content', 0 )->innerHtml`, I'm still digging in to see why.

**Comment by paquettg** [comment]
all white space is reduced to a single space. This includes line breaks.

**Comment by sc0ttkclark** [comment]
This is something that happens as part of SimpleXMLElement, not php-html-parser, but posting for posterity here to help others in the future:

```php
// Replace line breaks temporarily (hack)
$html = str_replace( '&#10;', "\n", $content );

// Load into Dom
$dom = new Dom;
$dom->load( $html );

// Do what you need to do with your processing

// Get any piece of content
$some_content = $dom->find( '.content', 0 )->innerHtml;

// Replace temporary hack with proper line breaks
$some_content = str_replace( "\n", '&#10;', $some_content );

// Now you are golden :)
```

This replaces line breaks `\n` with an HTML entity `&#10;`, which you can then replace back when you're ready to get the content out which may require line breaks.
