### ISSUE TITLE
Incorrect behaviour on parsing html

### ISSUE THREAD

**Issue by behzadsh** [paquettg/php-html-parser#41]
I was trying to pars html content of cnn.com news pages, and when I get body tag, using both `find()` and  `getElementByTag()` half the content was gone. I put parsed content into a file, and realized some tags like `<article>` are out of `<body>` or `<html>` tag, something like this:

```html
<html>
  <head>...</head>
  <body>...</body>
  <article>...</article>
  <div>...</div>
</html>
<div>...</div>
```

php code:
```php
<?php

$dom = new PHPHtmlParser\Dom();
$url = 'http://edition.cnn.com/2015/11/19/tennis/world-tour-finals-federer-nishikori/index.html';
$dom->load($url);
file_put_contents('test.html', (string) $dom);
```

**Comment by paquettg** [comment]
Ah, the code base at the moment only cares about what is in the html tag.... we can most likely solve this by given the option to contain multiple root nodes but at the moment that is not possible.

**Comment by paquettg** [comment]
I am not able to duplicate your issue, please reopen if you are stil experience your issue with more details and I will continue to look into it.
