### ISSUE TITLE
How do you delete nodes?

### ISSUE THREAD

**Issue by kokarn** [paquettg/php-html-parser#43]
Hello!

I'm trying to do some easy html manipulation and I can't seem to figure it out.

According to the docs for [sunra/php-simple-html-dom-parser](http://simplehtmldom.sourceforge.net/manual.htm) which I figure should work (correct me if i'm wrong) you should be able to do this.
```php
// Remove a element, set it's outertext as an empty string 
$e->outertext = '';
```

But in my testcase, that doesn't seem to work. 
This is the relevant part of my code

```php
$dom = new Dom;
$dom->loadStr( $pageMarkup, [] );
$menu = $dom->find( '.inPageMenu' );
$menu->outertext = '';
$html = $dom->outerHtml;
```
After that, the item with the class is still present in ```$html```.

Am I going at this backwards or am I missing something? 
Thanks in advance!

**Comment by tdlm** [comment]
:+1:

**Comment by paquettg** [comment]
At the moment their is no way to delete the node, the way it was done in the sunra does not work in this version of the plugin.

I'll add this feature though.
