### ISSUE TITLE
Space before closing > parsed incorrectly

### ISSUE THREAD

**Issue by js-25000** [paquettg/php-html-parser#45]
Hi,

If you have a space before the closing > in a tag, this library incorrectly assumes the following text is a set of attributes for the tag. Eg 
```
<a href="http://www.example.com" >This is text</a>
```
The a node will then have the following attributes: href, This, is, text.

**Comment by shtse8** [comment]
I have the same problem

**Comment by shtse8** [comment]
`<div class="stream-container  "
    >

      <div class="stream-item js-new-items-bar-container">
</div>

    <div class="stream">`
will be pared as 
`<div class="stream-item js-new-items-bar-container" <div> </div> <div class="stream"> `

**Comment by macinsauce** [comment]
I ran into the same issue, and I believe this is also happening in issue #49 where the library won't load the full html of a page correctly. Inserting the following line of code into the [clean method](https://github.com/paquettg/php-html-parser/blob/master/src/PHPHtmlParser/Dom.php#L360) could be a potential fix:

`$str = str_replace('" >', '">"', $str);`

**Comment by DaveChild** [comment]
The same issue still happens where there is a tag with a space before the closing > but where it has no attributes, e.g.: `<li >`.
