### ISSUE TITLE
Load HTML Incompletely 

### ISSUE THREAD

**Issue by hariesnurikhwan** [paquettg/php-html-parser#49]
Here's my code.

```
use PHPHtmlParser\Dom;

$dom = new Dom;
$dom->load('http://example.com');
$html = $dom->outerHtml;
echo $html;
```

When I view-source, the html isn't load completely. It just load like half of the html page only.
For some reason I can't expose the real URL here.

**Comment by paquettg** [comment]
This issue should be solved by the solution to #45, so I am closing this issue also.
