### ISSUE TITLE
preserveLineBreaks option doesn't work

### ISSUE THREAD

**Issue by exeQutor** [paquettg/php-html-parser#50]
Setting the preserveLineBreaks option to TRUE doesn't seem to work.

**Comment by exeQutor** [comment]
Oops. Sorry. It's a different issue. I installed 1.6.8 via composer, but the copy I got isn't the same as the one in this repository - it's older. It doesn't have the preserveLineBreaks option.

How do I properly install this via composer? I have used the following:

```
composer require paquettg/php-html-parser
```

**Comment by paquettg** [comment]
you can require the 'dev-master' version if you want the most recent developed code.

https://packagist.org/packages/paquettg/php-html-parser#dev-master
