### ISSUE TITLE
[Request] Replace child node

### ISSUE THREAD

**Issue by hissy** [paquettg/php-html-parser#52]
Currently we are able to remove specific child and add new child in the tail of the parent, but we can't replace specific tag node.

sunra/php-simple-html-dom-parser can do this.

```php
$child->outertext = '<new />';
```

Here is my thought:

```php
$child = $parent->find('child')[0];
$newChild = new Tag('new');
$parent->replaceChild($child->id(), $newChild);
```

Thanks!

**Comment by tdlm** [comment]
:+1:

**Comment by paquettg** [comment]
I'll look into implementing this.

**Comment by hissy** [comment]
Thanks! :+1:
