### ISSUE TITLE
[Request] Wildcard symbol?

### ISSUE THREAD

**Issue by YamiOdymel** [paquettg/php-html-parser#53]
I was trying to get all the elements,

here's what I tried:

```php
$dom->load('<div class="all"><p>Hey bro, <a href="google.com">click here</a><br /> :)</p></div>');
$a   = $dom->find('*');

exit(var_dump($a)));
```

It returns 1(int), it seems like php-html-parser doesn't support the wildcard symbol?

**Comment by paquettg** [comment]
I am not getting this issue when attempting to use the exit on the var_dump using the same code.

If you are still getting this issue please open a new issue with more detail, thanks.
