### ISSUE TITLE
Can not get all content in body tag

### ISSUE THREAD

**Issue by phuclh** [paquettg/php-html-parser#55]
```
$this->dom = new Dom;
$this->dom->loadFromUrl($url);

$this->dom->find('body')->innerHtml;
```

But it just get a part of content in body tag. I don't understand the reason? May you help me. Thank you.

This is my URL: `http://casiovietnam.net/dong-ho-dien-tu-casio-f91wg9sdf-dong-co-dien`

**Comment by phuclh** [comment]
Somebody help me, pls !!!!

**Comment by paquettg** [comment]
I am not able to duplicate your
