### ISSUE TITLE
[Proposal] Add removeAttribute and removeAttributes methods to Tag class

### ISSUE THREAD

**Issue by lussoluca** [paquettg/php-html-parser#57]
It would be very useful if were possible to remove an attribute (or a list of attributes) from a tag. Ideally we can add two new methods both to the AbstractNode and the Tag classes. The first method, removeAttribute, just removes an attributes. The second method, removeAttributes, removes all attributes from a tag except the ones passed to the method.

**Comment by paquettg** [comment]
You can already add attributes by using

`$node->getTag()->setAttribute('key', 'value');`

I'll add `removeAttribute('key');` and add a short cut do you can go

`$node->tag->setAttribute('key', 'value');

so you can write less code to modify the tag.
