### ISSUE TITLE
Parser corrupts my input by cleaning contents of divs and replace it with iv> for some reason

### ISSUE THREAD

**Issue by Ma-ve** [paquettg/php-html-parser#58]
This is the input I feed to php-html-parser: 

[matchstats2301484-b0f319a362db1f67e36f4702a9970e53.txt](https://github.com/paquettg/php-html-parser/files/181075/matchstats2301484-b0f319a362db1f67e36f4702a9970e53.txt)

    $content = file_get_contents('file.html');
    $dom = new Dom();
    $container = $dom->loadStr($content, []);
    echo $container->innerHtml;

gives

![fojmq](https://cloud.githubusercontent.com/assets/11227996/13901827/1f86b85e-ee31-11e5-810a-623d0bdc21b1.png)

Any clue as to what causes this? I've tried all options, but nothing changes.

**Comment by paquettg** [comment]
I am not able to duplicate your issue, could you provide me with the output from the innerhtml method please?
