### ISSUE TITLE
How to check if it's unable to find to prevent the error page

### ISSUE THREAD

**Issue by sullysheperd** [paquettg/php-html-parser#59]
Hi
I'm using this simple codes to catch a field from an external URL:

```
$dom = new Dom;
$dom->loadFromUrl($dom_address);
$time = $dom->getElementsByClass('exampleclass')->getAttribute('data-datetime');
```
        
The problem is, when it can't find the element containing that class for example the website is not working fine(goes offline or even when displays a 404 page) I get a php error(it's fine when it CAN find it). So how can I check to see if it can't find it, to simply set $time = 'N/A'; and prevent the page error. 

Thanks

**Comment by paquettg** [comment]
I am assuming the error is along the lines of 'calling a member function 'getAttribute' on a non-object'?

If that is the case then the following code should solve the issue.
`$dom = new Dom;
$dom->loadFromUrl($dom_address);
$class = $dom->getElementsByClass('exampleclass');
$time = null;
if (count($class) > 0) {
 $time = $class->getAttribute('data-datetime');
}`
