### ISSUE TITLE
<code> tag is not recognized

### ISSUE THREAD

**Issue by manfredjb** [paquettg/php-html-parser#60]
This is the HTML:

    <strong>hello</strong>
    <code class="language-php">$foo = "bar";</code>

The parser only recognizes `<strong>` according to the output:

> there are 1 nodes
- strong

```php
$dom = new Dom;
$dom->load('<strong>hello</strong><code class="language-php">$foo = "bar";</code>');
$nodes = $dom->find('*');
$total = count($nodes);
echo "there are {$total} nodes";
/** @var Dom\AbstractNode $node*/
foreach ($nodes as $node) {
    $tag = $node->getTag();
    echo "<br>- {$tag->name()}";
}
```

Any idea why `<code>` is ignored? I have tested a lot of tags and only this one is  not recognized. Thank you in advance.

**Comment by paquettg** [comment]
hey @manfredjb,

we remove the <code> tag as part of the clean up as this tag is a preformmated tag. This would seem to be something that was part of the of the original code base and I don't see a reason for this tag to be cleaned up. 

I'll remove the clean up and run some tests, if all goes well I'll push a solution to your problem.
