### ISSUE TITLE
Add a method for TextNode that can be reset the text for the node.

### ISSUE THREAD

**Issue by KomaBeyond** [paquettg/php-html-parser#61]
Just like the title what i said, i think it will be useful!

**Comment by paquettg** [comment]
What do you mean reset?

Do you mean the original text of the node? How do you see this working?

**Comment by KomaBeyond** [comment]
For example, when the textNode it's val is "aa", and then i want to change it into "bb", so i need a method to do this. Just like i can changed the label attr.

**Comment by dengsn** [comment]
Indeed a method to change the text of a node would be useful. Now I have to use a workaround, first deleting all children of the node and then adding a new `TextNode` as a child.

**Comment by paquettg** [comment]
added method
da5afae3f4905cc8ac20ebf64fb06a25ba5d5ee9
