### ISSUE TITLE
Multiple class selector does not work

### ISSUE THREAD

**Issue by mwaggonerstashimi** [paquettg/php-html-parser#65]
Using 1.7.0, selectors of the style "a.b.c" do not correctly find elements with multiple classes.

index.php:

`<?php`
`require_once("vendor/autoload.php");`
`$dom = new \PHPHtmlParser\Dom();`
`$dom->loadFromFile("fake.html");`
`$A = $dom->find("a.b");`
`var_dump(count($A));`
`$B = $dom->find("a.b.c");`
`var_dump(count($B));`

fake.html:

`<a class="b">alpha</a>`
`<a class="b c">bravo</a>`

output:

`$ php -f index.php`
`int(2)`
`int(0)`
`$`

I wouldn't necessarily consider this a bug, except the documentation says that "any CSS selector" can be used, which is not the case here. I also tested with 1.6.4 and 1.6.9, with the same results.

Thanks!

**Comment by feicanfly** [comment]
it seems i have the same issues.

**Comment by waza123x** [comment]
same shit

**Comment by leotm** [comment]
Try: `find("a[class=b c]")`

**Comment by KnufflPuffl** [comment]
Hi same issue here

**Comment by mossman07** [comment]
Hi same issue here
