### ISSUE TITLE
[Proposal] Replace child node with node array

### ISSUE THREAD

**Issue by hao-li** [paquettg/php-html-parser#67]
Currently we are able to replace a tag node with another one(#52), but we can't replace a tag node with several nodes.

sunra/php-simple-html-dom-parser can do this.

``` php
$child->outertext = $child->innertext;
```

Here is my thought:

``` php
$child = $parent->find('child')[0];
$children = $child->getChildren();
$parent->replaceChild($child->id(), $children);
```

Thanks!

**Comment by paquettg** [comment]
done
