### ISSUE TITLE
Problem with spesific website

### ISSUE THREAD

**Issue by HACKHERS** [paquettg/php-html-parser#68]
Hey folks, I'm trying to use parser in one of the websites (code below) but seems like parser cannot get whole website data. I tried with 'file_get_contents' and $dom->load still doesn't work at all.

```
require "vendor/autoload.php";
use PHPHtmlParser\Dom;

$races = ['Karu', 'Elmo'];

$dom = new Dom;
$dom->loadFromUrl('www.nttgameonline.com/knight/en/ranking/clan/0/Karu');
$html = $dom->innerHtml;

$contents = $dom->find('#server');
echo count($contents); // It should print 4

foreach ($contents as $content)
{     
    echo ($content->plaintext);   
}

```

**Comment by paquettg** [comment]
hey @HACKHERS 

The plaintext attribute is not a supported attribute for the nodes. You can always use the `innerhtml` attribute and then escape the html of the returning text, that should give you the same results.
