### ISSUE TITLE
wrapping HtmlNode with another one

### ISSUE THREAD

**Issue by Venzon** [paquettg/php-html-parser#7]
Is there any option to wrap existing nodes with new ones or some way to change node attributes?

**Comment by paquettg** [comment]
I added a method to the nodes called 'setAttribute' that will allow you to change the attribute of a node.

You can Always create new nodes and add an existing node as a child node but, at the moment, there is no way to insert that new parent node into an existing dom tree. I'll create a new feature request for this feature itself as I could see it being useful.
