### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by waza123x** [paquettg/php-html-parser#71]
Eats a lot of memory when use it in loop.

```
function my($buf){
        ...
        $dom->load($buf);
        $a = $dom->find('#some');
        $dom->load($a->innerHTML);
        $a = $dom->find("a");
        foreach ($a as $content){
              my($buf);
        ...
       }
}

```

any function to clear memory in loop ?
$dom = null;
$a = null;
in loop do not help.

**Comment by waza123x** [comment]
had to make bat script which will run php file in loop, stupid memory leak.

**Comment by leotm** [comment]
Noticing it creating an Apache process per run eating up to 35% of my CPU (i7 920 @ 3.5 Ghz), which have to manually close each time.

Have loops running to detect and scrape URLs from each page of pagination, then exit.

Simple `unset()` per URL scrape isn't doing the trick either.
_Simple HTML DOM Parser_ had a `clear()` function that worked.

Unfortunately my shell scripting sucks but if you could share/attach your .bat script, I'll try to adapt it.
