### ISSUE TITLE
[Request] plain text: extract contents from html

### ISSUE THREAD

**Issue by grzhan** [paquettg/php-html-parser#72]
[sunra/php-simple-html-dom-parser](https://github.com/sunra/php-simple-html-dom-parser) can dump contents (without tags) from HTML:

`echo file_get_html('http://www.google.com/')->plaintext; `

I want the same feature in php-html-parser. 

Now, when I use `$dom->text`, I only get the text content of this node without its descendants:

```
$dom = new Dom;
$dom->load('foo<p>bar</p>');
echo $dom->text; // will output 'foo'
```

How about adding an property named `plainText` or `textContent` in `Dom` class?

By the way, thank you for this cool parser :)

**Comment by waza123x** [comment]
try

`echo strip_tags($dom->innerHTML);`

**Comment by grzhan** [comment]
@waza123x thanks for your solution!
