### ISSUE TITLE
[Request] Why children is not accessible on AbstractNode?

### ISSUE THREAD

**Issue by kurorido** [paquettg/php-html-parser#76]
There has outerhtml, innerhtml, text, tag, parent but why don't make children accessible?

> ```
> public function __get($key)
> {
>     // check attribute first
>     if ( ! is_null($this->getAttribute($key))) {
>         return $this->getAttribute($key);
>     }
>     switch (strtolower($key)) {
>         case 'outerhtml':
>             return $this->outerHtml();
>         case 'innerhtml':
>             return $this->innerHtml();
>         case 'text':
>             return $this->text();
>         case 'tag':
>             return $this->getTag();
>         case 'parent':
>             $this->getParent();
>     }
> 
>     return null;
> }
> ```

**Comment by paquettg** [comment]
Hey Kurorido,

The reason I did not ad Children as part of the abstract node is because not all nodes have the children. I add logic for children in the Innernode object as LeadNode objects do not need this extra information.

Hope that helps.
