### ISSUE TITLE
Badly formatted HTML causes PHP maximum nested calls reached.

### ISSUE THREAD

**Issue by thinkingmedia** [paquettg/php-html-parser#78]
I was trying to parse the HTML from a large collection of URLS, and this website was in the list.

http://www.weather.gov/

HTML validation shows that the `<area>` tag is not closed in the document.

https://validator.w3.org/check?uri=http%3A%2F%2Fwww.weather.gov%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

I think this triggered this error.

```
Fatal error: Maximum function nesting level of '256' reached, aborting! in C:\work\tags\web\vendor\paquettg\php-html-parser\src\PHPHtmlParser\Dom\AbstractNode.php on line 212
```

I do pre-process the HTML with Tidy but it doesn't prevent this failure.

I'm not asking that the parser be able to handle invalid HTML, but the issue for me is that this is a critical PHP error. It can not be caught with a try/catch and causes PHP to just crash.

Is there any kind of fix that could be added to prevent this edge case from triggering a fatal error?

**Comment by paquettg** [comment]
You can now change php settings to throw expections in cases like these so you should be able to catch these errors going forward.
