### ISSUE TITLE
class TextNode have a encoding bug

### ISSUE THREAD

**Issue by liuyuqiang** [paquettg/php-html-parser#8]
public function __construct($text)
	{
		// remove double spaces
		$text = preg_replace('/\s+/', ' ', $text);

$text = preg_replace('/\s+/', ' ', $text);  

there are encoding bug. deleted just fine.

test case:

        $dom = new \PHPHtmlParser\Dom;
        $dom->load(
        ' <div class="content">'.
        '            一哥们开车巨慢，早上上班十几公里路能开四十多分钟，每天起很早为了不迟到，经常见一骑三轮车的保洁老大爷晃晃悠悠超他的车对他说:小伙子又早起练车呀，快点开吧，交警一会就上班了。。。'.
        '        </div>'
        );
        $content = $dom->find('div.content');
        var_dump($content[0]->innerHtml);exit;

maybe have a better solution。

**Comment by ccn** [comment]
if $text holds text encoded as UTF-8, we need to use /u pattern modifier.

$text = "公"; // "\xe5\x85\xac"
$text = preg_replace('/\s+/', ' ', $text);
$text will become \xe5\x20\xac

but, in constructor, we don't know the text's encoding.
