### ISSUE TITLE
Parser incorrectly collapses whitespace 

### ISSUE THREAD

**Issue by ZhangYiJiang** [paquettg/php-html-parser#80]
**To reproduce:** Run the following

```
$dom = new Dom();
$dom->load('<pre>    Hello world</pre>');
echo $dom; 
```

**Result:** 

```
=> "<pre> Hello world</pre>"
```

The resultant HTML has its four spaces collapsed to one. This will break any use cases for whitespace sensitive HTML (such as in `<pre>` tags), and is just bad practise in general, since the parser is silently modifying the HTML. The `whitespaceTextNode` should already be enabled by default, but even with it enabled manually this still occurs.

**Comment by AndyGCook** [comment]
@ZhangYiJiang Did you ever find a fix for this? Dealing with this in my <pre> tags right now...

**Comment by ZhangYiJiang** [comment]
@AndyGCook  Ended up switching to https://github.com/Masterminds/html5-php. It's still not perfect, but it does work better than this, which seems unmaintained
