### ISSUE TITLE
Problem with HtmlNode::textWithChildren

### ISSUE THREAD

**Issue by yarsoniy** [paquettg/php-html-parser#85]
There is a problem with HtmlNode.
1. You get content with $node->text(true).
2. Then you remove some of it's child nodes.
3. And fetch content with $node->text(true) again.
As a result you will get the the same value as with first call. But actual content is different now.

To fix it HtmlNode::clear() has to reset the value of $this->textWithChildren as well as $this->text.
Thanks.

**Comment by paquettg** [comment]
Fixed in 2.0.1
