### ISSUE TITLE
[Bug] Cannot find element only be attribute name

### ISSUE THREAD

**Issue by oleg-andreyev** [paquettg/php-html-parser#95]
It should be possible to find tags only by attribute name: `[attr-name]`
Right now it's impossible because:

```
if ($rule['key'] != 'plaintext' && is_null($child->getAttribute($rule['key']))) {
  $pass = false;
}
```

Is forcing that have an value

**Comment by maxstar** [comment]
Actual problem: you can't find tag by attribute if this attribute does not have value.
`<any-tag attribute>something</any-tag>`

**Comment by paquettg** [comment]
merged PR
