### ISSUE TITLE
 (SSL certificate problem: self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by hikmat30ce** [paquettg/php-html-parser#98]
(SSL certificate problem: self signed certificate in certificate chain) error when deployed in production environment.
I have identified if we add 
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
in curl.php then it will resolve the issue!

please advise if there is any other alternative

**Comment by mallardduck** [comment]
It looks like the site you're using this on doesn't have a valid SSL.


I'd suggest you use Guzzle(or PHP's plain curl) manually to grab the page HTML and pass that to the parser manually. Keep in mind I don't know what your use case is, but I'll include an example of what I'd do bellow:

```
$client = new GuzzleHttp\Client();
$response = $client->request('GET', 'https://expired.badssl.com/', ['verify' => false]);
$html = (string) $response->getBody();
$domCrawler = (new Dom)->load($html);
```

By doing it this way you have a little more control over how requests are made; it won't affect how the library is used overall, just how you get the library the HTML data.

**Comment by hikmat30ce** [comment]
yeah that worked

thanks
