### ISSUE TITLE
[Bug] ReplaceChild must call clear() on current node

### ISSUE THREAD

**Issue by maxstar** [paquettg/php-html-parser#99]
outerHtml is not updated after ReplaceChild is called which results in incorrect string output.

**Comment by maxstar** [comment]
ReplaceChild also looses next/prev links

**Comment by mallardduck** [comment]
The PR I made, #101 addresses this issue.

It looks like #88 is also tangentially related to these issues.
It's all a symptom of DOM/HTML cache not being cleared corrected when classes are modified.

**Comment by paquettg** [comment]
merged PR
